var http = require('http')
var str = require('./config')
var foo = require('foo')
http.createServer(function(req,res){
    console.log(str)
    console.log(foo)
    res.writeHead(200,{'Content-Type':'text/html;charset="utf-8"'})
    res.write("demo1中文")
    res.end()
}).listen(8001,'127.0.0.1')